// index.js

// Import the WASM package (generated by wasm-pack)
import init, { run } from './pkg';  // Make sure './pkg' points to the correct path

// Initialize the WASM module
init().then(() => {
  // Call the entry point function exported from Rust
  run();
}).catch(console.error);

