[package]
name = "wbwrk-text-input"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3", features = [
  "console", 
  # "Document", 
  # "HtmlInputElement", 
  # "Window", 
]}
